
contact_links:
 - name: Common Voice Discourse 
    url: https://discourse.mozilla.org/t/common-voice-community-playbook-v1-2-review/83030
    about: If you would like to discuss an issue please use this discourse topic
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
